[build]
  publish = "src"
  command = "echo 'No build command'"

[[redirects]]
  from = "/*"
  to = "/src/index.html"
  status = 200

[[redirects]]
  from = "/achat"
  to = "/src/achat.html"
  status = 200

[[redirects]]
  from = "/success"
  to = "/src/success.html"
  status = 200