[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/css/*"
  to = "/css/:splat"
  status = 200

[[redirects]]
  from = "/js/*"
  to = "/js/:splat"
  status = 200

[[redirects]]
  from = "/images/*"
  to = "/images/:splat"
  status = 200

[[redirects]]
  from = "/json/*"
  to = "/json/:splat"
  status = 200

[[redirects]]
  from = "/public/*"
  to = "/public/:splat"
  status = 200

# Single Page Application (SPA) redirects
[[redirects]]
  from = "/cart/*"
  to = "/cart/index.html"
  status = 200

[[redirects]]
  from = "/checkout/*"
  to = "/checkout/index.html"
  status = 200

# Error handling
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404